version: "3.8"

services:
  redis:
    image: redis:7
    container_name: reachinbox-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: reachinbox-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: reachinbox
    ports:
      - "5432:5432"
